export enum ActionTypes {
    // SCHEMA
    SCHEMA_FETCH = 'SCHEMA_FETCH',
    SCHEMA_ERROR = 'SCHEMA_ERROR',
    SCHEMA_SUCCESS = 'SCHEMA_SUCCESS',
    // DATA
    DATA_FETCH = 'DATA_FETCH',
    DATA_ERROR = 'DATA_ERROR',
    DATA_SUCCESS = 'DATA_SUCCESS',
    // DETAIL
    DETAIL_COMMAND = 'DETAIL_COMMAND',
    DETAIL_COMMAND_RESULT = 'DETAIL_COMMAND_RESULT',
    // LIST
    LIST_SELECTED_ROW = 'LIST_SELECTED_ROW',
    LIST_COMMAND = 'LIST_COMMAND',
    LIST_COMMAND_RESULT = 'LIST_COMMAND_RESULT'
}

