export enum ActionTypes {
    // UI
    UI_ERROR = 'UI_ERROR',
    UI_CHANGE_ROW = 'UI_CHANGE_ROW',
    UI_COMMAND = 'UI_COMMAND',
    UI_COMMAND_RESULT = 'UI_COMMAND_RESULT',
    // SCHEMA
    SCHEMA_FETCH = 'SCHEMA_FETCH',
    SCHEMA_ERROR = 'SCHEMA_ERROR',
    SCHEMA_SUCCESS = 'SCHEMA_SUCCESS',
    // DATA
    DATA_FETCH = 'DATA_FETCH',
    DATA_ERROR = 'DATA_ERROR',
    DATA_SUCCESS = 'DATA_SUCCESS'
}
